# emlcal — build, test and install.
#
#   make              build ./emlcal
#   make install      copy it to ~/.local/bin (override with PREFIX= or BINDIR=)
#   make check        what CI runs: gofmt, vet, race tests

BIN  := emlcal
PKG  := ./cmd/emlcal

PREFIX ?= $(HOME)/.local
BINDIR ?= $(PREFIX)/bin

GO          ?= go
GOFLAGS     ?=
CGO_ENABLED ?= 0

SOURCES := $(shell find . -name '*.go' -not -path './.git/*') go.mod go.sum

.DEFAULT_GOAL := build

.PHONY: build
build: $(BIN)

$(BIN): $(SOURCES)
	CGO_ENABLED=$(CGO_ENABLED) $(GO) build $(GOFLAGS) -o $@ $(PKG)

.PHONY: install
install: $(BIN)
	install -d $(DESTDIR)$(BINDIR)
	install -m 0755 $(BIN) $(DESTDIR)$(BINDIR)/$(BIN)
	@echo "installed $(DESTDIR)$(BINDIR)/$(BIN)"
	@case ":$$PATH:" in *":$(BINDIR):"*) ;; \
	  *) echo "warning: $(BINDIR) is not in your PATH" ;; esac

.PHONY: uninstall
uninstall:
	rm -f $(DESTDIR)$(BINDIR)/$(BIN)

# Shell completions, generated by the binary itself. Separate from `install`
# because it writes outside $(BINDIR).
.PHONY: install-completions
install-completions: $(BIN)
	install -d $(DESTDIR)$(PREFIX)/share/bash-completion/completions
	./$(BIN) completion bash > $(DESTDIR)$(PREFIX)/share/bash-completion/completions/$(BIN)
	install -d $(DESTDIR)$(PREFIX)/share/zsh/site-functions
	./$(BIN) completion zsh > $(DESTDIR)$(PREFIX)/share/zsh/site-functions/_$(BIN)
	install -d $(DESTDIR)$(HOME)/.config/fish/completions
	./$(BIN) completion fish > $(DESTDIR)$(HOME)/.config/fish/completions/$(BIN).fish

.PHONY: test
test:
	$(GO) test -race -count=1 ./...

.PHONY: fmt
fmt:
	gofmt -l -w .

.PHONY: vet
vet:
	$(GO) vet ./...

.PHONY: check
check:
	@test -z "$$(gofmt -l .)" || { gofmt -l .; echo "run 'make fmt'"; exit 1; }
	$(GO) vet ./...
	$(GO) test -race -count=1 ./...

.PHONY: clean
clean:
	rm -f $(BIN) coverage.out
